### ISSUE TITLE
setPeakList == setPeaks?

### ISSUE THREAD

**Issue by epoyraz** [PRIDE-Toolsuite/inspector-mzgraph-browser#3]
Hi,

in the README.MD the spectrum has a method called setPeakList.
This method doesn't seem to exist. I guess the method is now called setPeaks.

Not sure, though.

**Comment by ypriverol** [comment]
@epoyraz feel free to create a pull request with this and other changes. It would be interesting if you change something and improve the visualizations to make a deploy and see this improvements in the present version of the inspector.
